[package]
name = "websocket"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1_smol = "1.0.0"
base64 = "0.13.0"
# tungstenite = "0.17.2"